name: CI - Build & Test FastAPI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        working-directory: infra/backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint Code (flake8)
        working-directory: infra/backend
        run: |
          pip install flake8
          flake8 --ignore=E501 .

      - name: Build Docker Image
        run: |
          docker build -t fastapi-library ./infra/backend